### ISSUE TITLE
Remove the LFS

### ISSUE THREAD

**Issue by tiziodcaio** [signalapp/better-sqlite3#5]
Please remove the LFS so I can upgrade the main repository to yarn berry, thanks

**Comment by tiziodcaio** [comment]
yarnpkg/berry#3348

**Comment by indutny-signal** [comment]
Done!

**Comment by aguynamedben** [comment]
@indutny-signal Thank you! Any details on how this was fixed? we were keeping a local deps/ folder... has the install process been reworked where it just downloads the SQLite from a Signal server or something? 🙏

**Comment by aguynamedben** [comment]
I see now, cool.

**Comment by indutny-signal** [comment]
Yup, it just downloads it from an S3 bucket.
